apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-arm
  labels:
    app: hello-arm
    app.kubernetes.io/instance: "a17cdc20-378b-4c57-b16a-91f8cdcb3dc2"
    app.armada.ai/name: "hello-arm"
    app.armada.ai/type: "armada"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-arm
      app.kubernetes.io/instance: "a17cdc20-378b-4c57-b16a-91f8cdcb3dc2"
      app.armada.ai/name: "hello-arm"
      app.armada.ai/type: "armada"
  template:
    metadata:
      labels:
        app: hello-arm
        app.kubernetes.io/instance: "a17cdc20-378b-4c57-b16a-91f8cdcb3dc2"
        app.armada.ai/name: "hello-arm"
        app.armada.ai/type: "armada"
    spec:
      containers:
        - name: hello-arm
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: hello-arm-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-arm-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Hello World</title>
    </head>
    <body>
      <h1>Hello, World!</h1>
      <p>This is a simple HTML app deployed using ArgoCD.</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: hello-arm-service
spec:
  selector:
    app: hello-arm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
